require 'combinatorics/cartesian_product'
require 'combinatorics/choose'
require 'combinatorics/derange'
require 'combinatorics/extensions'
require 'combinatorics/list_comprehension'
require 'combinatorics/power_set'
require 'combinatorics/rearrange'
require 'combinatorics/version'
